/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b3551897-ec99-40f3-91ec-ce6f86276978",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_qevDYo2A9",
    "aws_user_pools_web_client_id": "13simqk92hrhjib83mpuckl2rk",
    "oauth": {},
    "aws_user_files_s3_bucket": "voicerecorder697208164bce4c0c99fd0ee85367bcef144054-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
